#!/usr/bin/env bash
# This file modified from k8s
# https://github.com/kubernetes/kubernetes/blob/master/hooks/pre-commit
# Now It's removed, The Reason is https://github.com/kubernetes/community/issues/729
# The PR is https://github.com/kubernetes/kubernetes/pull/47673

# How to use this hook?
# ln -fs ../../hooks/pre-commit .git/hooks/pre-commit
# In case hook is not executable
# chmod +x .git/hooks/pre-commit

readonly reset=$(tput sgr0)
readonly red=$(tput bold; tput setaf 1)
readonly green=$(tput bold; tput setaf 2)

exit_code=0

echo -ne "Checking for files that need gofmt... "
files_need_gofmt=()
files=($(git diff --cached --name-only --diff-filter ACM | grep "\.go$" | grep -v -e "^_vendor"))
for file in "${files[@]}"; do
    # Check for files that fail gofmt.
    diff="$(git show ":${file}" | gofmt -s -d 2>&1)"
    if [[ -n "$diff" ]]; then
        files_need_gofmt+=("${file}")
    fi
done

if [[ "${#files_need_gofmt[@]}" -ne 0 ]]; then
    echo "${red}ERROR!"
    echo "Some files have not been gofmt'd. To fix these errors, "
    echo "copy and paste the following:"
    echo "  gofmt -s -w ${files_need_gofmt[@]}"
    exit_code=1
else
    echo "${green}OK"
fi
echo "${reset}"

# mpaas go mod check
echo -ne "Checking go mod... "
files_go_mod=()
files=("go.mod" "go.sum")
go mod tidy

for file in "${files[@]}"; do
    diff="$(git diff "${file}")"
    if [[ -n "$diff" ]]; then
        files_go_mod+=("${file}")
    fi
done

if [[ "${#files_go_mod[@]}" -ne 0 ]]; then
    echo "${red}ERROR!"
    echo "Some modules may missing or unused."
    exit_code=1
else
    echo "${green}OK"
fi
echo "${reset}"

if [[ "${exit_code}" != 0 ]]; then
    echo "${red}Aborting commit${reset}"
fi
exit ${exit_code}
